server:
  port: 8002

microservices:
  humidity: humidity-microservice
  temperature: temperature-microservice

spring:
  application:
    name: aggregator-microservice
  cloud:
    config:
      uri: http://localhost:8888/
  config:
    import: "configserver:"